name: Push

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main

      - name: Upload ROCK to ghcr.io
        run: |
          sudo snap install yq
          VERSION=$(yq -r '.version' rockcraft.yaml)

          sudo skopeo --insecure-policy copy \
            oci-archive:$(realpath ./jupyter-pytorch-full_*.rock) \
            docker://ghcr.io/canonical/jupyter-pytorch-full:$VERSION \
            --dest-creds "juju-charm-bot:${{ secrets.GHCR_TOKEN }}"

          sudo skopeo --insecure-policy copy \
            oci-archive:$(realpath ./jupyter-pytorch-full_*.rock) \
            docker://ghcr.io/canonical/jupyter-pytorch-full:latest \
            --dest-creds "juju-charm-bot:${{ secrets.GHCR_TOKEN }}"

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Create SBOM
        run: syft $(realpath ./jupyter-pytorch-full_*.rock) -o spdx-json=jupyter-pytorch-full.sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: jupyter-pytorch-full-sbom
          path: jupyter-pytorch-full.sbom.json
      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: jupyter-pytorch-full-rock
          path: "jupyter-pytorch-full_*.rock"
